method: onet
data:
  dataset: Shapes3D
  path: data/matterport
  loc: [48, 48, 80]
  scale: 160
  points_subsample: 2048
  input_type: sdfm
  voxels_file: null
  vis_split: vis
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder_kwargs: {z: 160}
  encoder: voxel_deep
  c_dim: 256
  z_dim: 0
training:
  out_dir:  out/sdf/matterport
  batch_size: 2
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 2500
  validate_every: 50000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  resolution_0: 96
  upsampling_steps: 0
