method: onet_color
data:
  dataset: Shapes3D
  path: data/ShapeNetSDF
  sdf_res: 96
  points_subsample: 2048
  input_type: sdf
  voxels_file: null
  vis_split: vis
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: voxel_deep
  c_dim: 256
  z_dim: 0
  encoder_geo_weights: /media/nihalsid/OSDisk/Users/ga83fiz/nihalsid/occupancy_networks/out/saved/onet_sdf.pt
training:
  out_dir:  out/sdf/onet_color
  batch_size: 2
  model_selection_metric: l1_color
  model_selection_mode: minimize
  visualize_every: 2500
  validate_every: 20000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
